### ISSUE TITLE
Issue with  black==19.3b0 for python 3.4

### ISSUE THREAD

**Issue by suryasr007** [sayanarijit/moodlmth#1]
For Python 3.4:

(venv) [suryav:~/moodlmth]$ pip install .                                                                         (master)
Processing /script/suryav/moodlmth
Collecting black==19.3b0 (from moodlmth==0.1.5)
  Could not find a version that satisfies the requirement black==19.3b0 (from moodlmth==0.1.5) (from versions: )
No matching distribution found for black==19.3b0 (from moodlmth==0.1.5)

**Comment by sayanarijit** [comment]
It supports only python >=3.6. same as the core library.
